Testing the code form https://github.com/akshayytiwari/adjusted_psi
For the purpose of converting to app through reactive programming
```{r}
library(ggplot2)
```

Point correction function.
```{r}
eps <- 1e-08
correction <- function(rho_c, psi_c, phi_c, alpha, beta) {
  numerator <- rho_c * (1 - rho_c) * (psi_c - 1 + phi_c) * (alpha + beta - 1)
  denominator <- (rho_c + beta - 1) * (psi_c * rho_c * (1 - alpha) - alpha * (1 - phi_c) * (1 - rho_c))
  denominator <- ifelse(abs(denominator) < eps, NA, denominator)

  psi_temp <- 1 - numerator / denominator
  psi <- ifelse(is.na(psi_temp) | psi_temp < 0 | psi_temp > 1, NA, psi_temp)
  
  c(psi)
}
```

Monte Carlo function.
```{r}
set.seed(123)
monte_carlo <- function (n, sp, sn, n_iter,
                         rho_c, psi_c, phi_c,
                         alpha_a, alpha_b, beta_a, beta_b) {
  
  alpha <- rbeta(n_iter, alpha_a, alpha_b)
  beta  <- rbeta(n_iter, beta_a, beta_b)
  rho_c <- rbinom(n_iter, n, rho_c) / n
  psi_c <- rbinom(n_iter, sp, psi_c) / sp
  phi_c <- rbinom(n_iter, sn, phi_c) / sn

  psi_hat <- correction(rho_c, psi_c, phi_c, alpha, beta)
  
  psi_l = quantile(psi_hat, probs = 0.25, na.rm = TRUE)
  psi = quantile(psi_hat, probs = 0.5, na.rm = TRUE)
  psi_u = quantile(psi_hat, probs = 0.75, na.rm = TRUE)
  
  #return(c(psi_l, psi, psi_u))
  return(psi_hat)
}
```

Carry out one cycle.
```{r}
n <- 31869
sp <- 849
sn <- 31020
n_iter <- 100000
rho_c <- 0.027
psi_c <- 0.121
phi_c <- 0.578
alpha <- 0.848
beta <- 1.0
alpha_a <- 100
alpha_b <- 17.3
beta_a <- 68.3
beta_b <- 0.2

psi_point <- correction(rho_c, psi_c, phi_c, alpha, beta)
psi_mc <- monte_carlo(n, sp, sn, n_iter,
                      rho_c, psi_c, phi_c,
                      alpha_a, alpha_b, beta_a, beta_b)

```

Plot.
```{r}
ggplot(data.frame(psi_mc <- psi_mc), aes(psi_mc)) + geom_density()
temp1 <- density(psi_mc, na.rm = TRUE)
plot(temp1$x, temp1$y)
```

testing further.
```{r}
estimate_beta <- function(q_vals, sen_range = c(0.5, 100), spe_range = c(0.5, 100)) {
  best_loss <- Inf
  best_params <- c(NA, NA)
  p_vals <- c(0.025, 0.5, 0.975)
  for (a in seq(sen_range[1], sen_range[2], length.out = 1000)) {
    for (b in seq(spe_range[1], spe_range[2], length.out = 1000)) {
      q_model <- qbeta(p_vals, a, b)
      loss <- sum((q_model - q_vals)^2)
      if (loss < best_loss) {
        best_loss <- loss
        best_params <- c(a, b)
      }
    }
  }
  return(data.frame(sen = best_params[1], spe = best_params[2]))
}

correction <- function(rho_c, psi_c, phi_c, alpha, beta) {
  numerator <- rho_c * (1 - rho_c) * (psi_c - 1 + phi_c) * (alpha + beta - 1)
  denominator <- (rho_c + beta - 1) * (psi_c * rho_c * (1 - alpha) - alpha * (1 - phi_c) * (1 - rho_c))
  denominator <- ifelse(abs(denominator) < 1e-08, NA, denominator)
  
  psi_temp <- 1 - numerator / denominator
  psi <- ifelse(is.na(psi_temp) | psi_temp < 0 | psi_temp > 1, NA, psi_temp)
  
  c(psi)
}


monte_carlo <- function (n, sp, sn, n_iter,
                         rho_c, psi_c, phi_c,
                         alpha_a, alpha_b, beta_a, beta_b) {
  set.seed(123)
  n_iter <- as.numeric(n_iter)
  alpha <- rbeta(n_iter, alpha_a, alpha_b)
  beta  <- rbeta(n_iter, beta_a, beta_b)
  rho_c <- rbinom(n_iter, n, rho_c) / n
  psi_c <- rbinom(n_iter, sp, psi_c) / sp
  phi_c <- rbinom(n_iter, sn, phi_c) / sn
  
  psi_hat <- correction(rho_c, psi_c, phi_c, alpha, beta)
  
  #psi_l = quantile(psi_hat, probs = 0.25, na.rm = TRUE)
  #psi = quantile(psi_hat, probs = 0.5, na.rm = TRUE)
  #psi_u = quantile(psi_hat, probs = 0.75, na.rm = TRUE)
  
  #return(c(psi_l, psi, psi_u))
  return(psi_hat)
}

```

Inputs.
```{r}
#alpha_l <- 0.75
#alpha1 <- 0.848
#alpha_u <- 0.9
#beta_l <- 0.9
#beta1 <- 0.9
#beta_u <- 1.0

#rho_c <- 0.027
#psi_c <- 0.121
#phi_c <- 0.578

#n <- 31869
#sp <- 849
#sn <- 31020
#n_iter <- 1000

alpha_l <- 0.924
alpha1 <- 0.967
alpha_u <- 0.986
beta_l <- 0.987
beta1 <- 0.995
beta_u <- 0.998

rho_c <- 0.028
psi_c <- 0.304
phi_c <- 0.432

n <- 13095
n_iter <- 100000

sp <- round(rho_c * n)
sn <- round((1 - rho_c) * n)

alpha <- estimate_beta(c(alpha_l, alpha1, alpha_u))
beta <- estimate_beta(c(beta_l, beta1, beta_u))

psi <- monte_carlo(n1, sp, sn, n_iter,
                                     rho_c, psi_c, phi_c,
                                     alpha$sen, alpha$spe, beta$sen, beta$spe)
```


